name: Trigger Probe of Deployed App on a CRON Schedule

on:
  schedule:
  # Runs "at minute 0 past every 12 hour" (see https://crontab.guru)... ie: every 12 hours
  - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:

  probe_deployed_app:
    runs-on: ubuntu-latest
    name: A job to probe deployed app
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install      
          
      # cache the dependencies from any node_modules directory
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json')}}    

      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        working-directory: ./probe-action
        with:
          args: probe
