name: Trigger Probe of Deployed App on a CRON Schedule

on:
  schedule:
  # Runs "at minute 0 past every 12 hour" (see https://crontab.guru)... ie: every 12 hours
  - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:

  probe_deployed_app:
    runs-on: ubuntu-latest
    name: A job to probe deployed app
    steps:
      # add git to the container and set it up with the token
      - name: setup git in container
        uses: actions/checkout@v3
          
      # cache the dependencies from any node_modules directory
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json')}}    

      # install the dependencies
      - name: install dependencies
        run: npm install puppeteer

      # install the dependencies
      - name: install chrome
        run: node node_modules/puppeteer/install.js

      - name: Probe Deployed App Action Step
        uses: ./probe-action # Uses an action in the probe-action directory
        id: probe
